name: Verify
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: volta-cli/action@v3
      - run: yarn
      - run: yarn build
      - run: yarn test
      - run: yarn lint:test
